// View에서 발생하는 모든 Action에 대한 응답코드를 정의한다.

// post에 대한 액션
export const POST_CREATE = "POST_CREATE";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";

export const POST_READ = "POST_READ";
export const POST_READ_SUCCESS = "POST_READ_SUCCESS";
export const POST_READ_FAILURE = "POST_READ_FAILURE";

export const POST_UPDATE = "POST_UPDATE";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAILURE = "POST_UPDATE_FAILURE";

export const POST_DELETE = "POST_DELETE";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";

export const FOOD_NEW = "FOOD_NEW";
export const FOOD_NEW_SUCCESS = "FOOD_NEW_SUCCESS";
export const FOOD_NEW_FAILURE = "FOOD_NEW_FAILURE";

export const FOOD_READ = "FOOD_READ";
export const FOOD_READ_SUCCESS = "FOOD_READ_SUCCESS";
export const FOOD_READ_FAILURE = "FOOD_READ_FAILURE";

export const FOOD_UPDATE = "FOOD_UPDATE";
export const FOOD_UPDATE_SUCCESS ="FOOD_UPDATE_SUCCESS";
export const FOOD_UPDATE_FAILURE = "FOOD_UPDATE_FAILURE";

export const FOOD_DELETE = "FOOD_DELETE";
export const FOOD_DELETE_SUCCESS = "FOOD_DELETE_SUCCESS";
export const FOOD_DELETE_FAILURE = "FOOD_DELETE_FAILURE";